# JavaScript library for reading EXIF image metadata.
# For more information: https://www.npmjs.com/package/exifreader
exif:
  enable: false
  template: "{FocalLength} f/{ApertureValue} {ExposureTime}s"
